services:
  harvester-deploy:
    build:
      context: .
      dockerfile: ./harvester/Dockerfile
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./harvest_config.yaml:/app/harvester/harvest_config.yaml
      - ./harvester_cache:/app/harvester/harvester_cache
      - ./harvest:/app/harvester/harvest
      - ./harvester_logs:/app/harvester/logs
    environment:
      - "HARVESTER_LOG_DIR=/app/harvester/logs"
      - "HARVEST_CONFIG_FILE=/app/harvester/harvest_config.yaml"
    env_file:
      - .env
