services:
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis-data:/var/lib/redis
      - ./redis-config/redis.conf:/usr/local/etc/redis/redis.conf
  db:
    image: "postgis/postgis:13-3.1-alpine"
    platform: linux/x86_64
    expose:
      - "5432"
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    environment:
      - "PGPORT=5432"
      - "POSTGRES_DB=$DB_NAME"
      - "POSTGRES_PASSWORD=$DB_PASSWORD"
      - "POSTGRES_USER=$DB_USER"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  web-api:
    build: ./web-api
    restart: always
    env_file:
      - .env
    expose:
      - "5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    deploy:
      replicas: 4
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./harvester_logs:/usr/share/nginx/html/harvester_logs:ro
    depends_on:
      - web-api
    ports:
      - "$NGINX_PORT:4000"
  scheduler:
    build:
      # Scheduler needs context ., see the dockerfile
      context: .
      dockerfile: ./download_scheduler/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    deploy:
      replicas: 2
    env_file:
      - .env
    environment:
      - "DOWNLOAD_WAF_URL=${APP_DOMAIN}/downloads"
    volumes:
      - downloads:/usr/src/app/download_scheduler/downloads
    restart: always
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: ${API_URL:-http://web-api:5000/api}
        BASE_URL: ${BASE_URL:-/}
    expose:
      - "80"
    depends_on:
      - web-api

  harvester:
    build:
      context: .
      dockerfile: ./harvester/Dockerfile
    profiles:
      - tools
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./harvest_config.yaml:/app/harvester/harvest_config.yaml
      - ./harvester_cache:/app/harvester/harvester_cache
      - ./harvest:/app/harvester/harvest
      - ./harvester_logs:/app/harvester/logs
    environment:
      - "HARVESTER_LOG_DIR=/app/harvester/logs"
    env_file:
      - .env
volumes:
  postgres-data:
  redis-data:
  downloads:
