# list of erddap URLs. Should end in /erddap
erddaps:
  - url: https://catalogue.hakai.org
    username: null
    password: null
    dataset_ids: []

# set to true to test with caching. Not available in production docker compose file
# defaults to false or a list of status_code to cache (e.g. [200, 404])
cache_requests: true

# defaults to 'harvest'
folder: ./downloads

log_level: debug
max_workers: 1
