[tool.poetry]
name = "cde"
version = "0.1.0"
description = "Python package for the CDE project"
authors = [
    "Nate Rosenstock",
    "Jorin Weatherston",
    "Mattew Brown",
    "Pramod Thupaki",
    "Jessy Barrette",
    "Mattew Foster",
    "Julien Robitaille"
]
readme = "README.md"
packages = [
    { include = "cde_harvester", from = "harvester" },
    { include = "erddap_downloader", from = "downloader" },
    { include = "cde_db_loader", from = "db-loader" },
    { include = "download_scheduler", from = "download_scheduler" }
]

[tool.poetry.dependencies]
python = "^3.10"
downloader = "^0.98"
anyio = "4.3.0"
black = "24.3.0"
certifi = "2024.2.2"
cftime = "1.6.3"
charset-normalizer = "3.3.2"
click = "8.1.7"
diskcache = "5.6.3"
erddap-python = "1.0.0"
erddapy = "2.2.0"
greenlet = "3.0.3"
h11 = "0.14.0"
httpcore = "1.0.5"
httpx = "0.27.0"
idna = "3.6"
isort = "5.13.2"
loguru = "0.7.2"
lxml = "5.1.0"
mypy-extensions = "1.0.0"
netcdf4 = "1.6.5"
numpy = "1.26.4"
packaging = "24.0"
pandas = "1.5.3"
pathspec = "0.12.1"
pdfkit = "1.0.0"
platformdirs = "4.2.0"
psycopg2-binary = "2.9.9"
python-dateutil = "2.9.0.post0"
python-dotenv = "1.0.1"
pytz = "2024.1"
pyyaml = "6.0.1"
requests = "2.31.0"
ruff = "0.3.4"
sentry-sdk = "1.43.0"
shapely = "2.0.3"
six = "1.16.0"
sniffio = "1.3.1"
sqlalchemy = "1.4.16"
typing-extensions = "4.10.0"
tzdata = "2024.1"
urllib3 = "2.2.1"
xarray = "2024.2.0"
jinja2 = "^3.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
