CDM_DATA_TYPE_UNSUPPORTED = "CDM_DATA_TYPE_UNSUPPORTED"
HTTP_ERROR = "HTTP_ERROR"
MISSING_REQUIRED_VARS = "MISSING_REQUIRED_VARS"
NO_SUPPORTED_VARIABLES = "NO_SUPPORTED_VARIABLES"
INGEST_FLAG_FALSE = "INGEST_FLAG_FALSE"
DEPTH_AND_ALTITUDE = "DEPTH_AND_ALTITUDE"
UNKNOWN_ERROR = "UNKNOWN_ERROR"
NO_PROFILES_FOUND = "NO_PROFILES_FOUND"
ON_SKIP_LIST = "ON_SKIP_LIST"
RESPONSE_TOO_LARGE = "RESPONSE_TOO_LARGE"
UNCHANGED = "UNCHANGED"


class ResponseTooLargeError(Exception):
    """An ERDDAP response exceeded MAX_RESPONSE_SIZE. Distinct from a generic
    error so the audit log can show RESPONSE_TOO_LARGE instead of UNKNOWN_ERROR
    (typically high-frequency datasets whose distinct()/enumeration is too big)."""
