"""Geographic filter for the OBIS harvester.

Limits OBIS occurrences to Canadian waters (EEZ + Canadian land territory).
Datasets contributed via the OBIS Canada or OTN-OBIS regional nodes are
exempt and harvested in their entirety.

The boundary polygon is loaded from the packaged
``cde_harvester/data/canada_eez_land.wkt`` file (regenerated by
``scripts/build_canada_eez_land_wkt.py``).
"""
import logging
from importlib.resources import files
from pathlib import Path

import numpy as np
from shapely import contains, points
from shapely import wkt as shp_wkt

logger = logging.getLogger(__name__)

DEFAULT_EXEMPT_NODE_IDS = frozenset({
    "7dfb2d90-9317-434d-8d4e-64adf324579a",   # OBIS Canada
    "68f83ea7-69a7-44fd-be77-3c3afd6f3cf8",   # OTN-OBIS
})


def _packaged_polygon_path() -> Path:
    return Path(str(files("cde_harvester.data") / "canada_eez_land.wkt"))


class ObisGeoFilter:
    """Decides whether an OBIS dataset is exempt and which occurrences to keep."""

    def __init__(self, mode="canada", polygon_file=None, exempt_node_ids=None):
        if mode not in ("canada", "none"):
            raise ValueError(f"Unsupported geo filter mode: {mode!r}")
        self.mode = mode
        self.exempt_node_ids = frozenset(exempt_node_ids) if exempt_node_ids else DEFAULT_EXEMPT_NODE_IDS
        self.polygon = None
        if mode == "canada":
            path = Path(polygon_file) if polygon_file else _packaged_polygon_path()
            self.polygon = shp_wkt.loads(path.read_text().strip())

    def is_exempt(self, metadata: dict) -> bool:
        """True when the dataset should be harvested in full (no geo filter applied)."""
        if self.mode == "none":
            return True
        for node in (metadata.get("nodes") or []):
            if node.get("id") in self.exempt_node_ids:
                return True
        return False

    def extent_intersects(self, extent_wkt):
        """True/False if a dataset extent intersects the boundary polygon.

        Returns ``None`` when the extent is missing, empty, or unparseable —
        the caller should fall through to fetching the full dataset.
        """
        if self.mode == "none" or not extent_wkt:
            return None
        try:
            return shp_wkt.loads(extent_wkt).intersects(self.polygon)
        except Exception as e:
            logger.warning("Could not parse dataset extent WKT: %s", e)
            return None

    def filter_points(self, lat, lon) -> np.ndarray:
        """Boolean mask: True where (lat, lon) is inside the boundary polygon.

        Vectorized via shapely 2.x. Coordinate convention is Point(x=lon, y=lat).
        """
        if self.mode == "none":
            return np.ones(len(lat), dtype=bool)
        return contains(self.polygon, points(lon, lat))
