-- Stable hex grid: give hexes_zoom_0/1 their natural key (i, j) so hex cells
-- are append-only and their pks stay stable across loads.
--
-- Background: create_hexes() used to DELETE both hex tables and re-tile the
-- whole data extent (from a moving ST_EstimatedExtent) on every load — full
-- rewrites of points/profiles/obis_cells/trajectory_cells followed, which
-- saturated the DB host and 504'd the site for minutes per harvest. PostGIS
-- hexagon grids are origin-anchored (cell (i, j) at a given size sits at a
-- fixed position regardless of the bounds argument), so a cell's identity is
-- (i, j) and its geometry never moves. The rewritten create_hexes()
-- (4_create_hexes.sql, re-applied after migrations on every deploy) upserts on
-- (i, j) and never deletes.
--
-- Because the old grid was generated by the same origin-anchored functions,
-- EXISTING hex rows already align with the global tiling: this migration just
-- backfills (i, j) in place from each cell's centroid. No renumbering, no FK
-- churn, no visible change to the serving tables.
--
-- Also drops points.hex_zoom_0/hex_zoom_1 (per-point copies of the hex
-- POLYGONS, plus two GIST indexes) — only the old create_hexes() read them.
--
-- Idempotent and guarded: every ALTER is skipped once applied, so re-running
-- on each deploy (db_migrate) does no work and takes no ACCESS EXCLUSIVE lock.
-- The i/j backfill re-runs on any row with NULL i (self-heals rows created by
-- an old create_hexes() racing a deploy). Wrapped in one transaction so a
-- partial application can't be observed.

BEGIN;

-- 1. Add (i, j) to the hex tables (guarded ALTER: no lock on re-run).
DO $$
DECLARE
  tbl text;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['hexes_zoom_0', 'hexes_zoom_1'] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_attribute
      WHERE attrelid = ('cde.' || tbl)::regclass AND attname = 'i' AND NOT attisdropped
    ) THEN
      EXECUTE format('ALTER TABLE cde.%I ADD COLUMN i integer, ADD COLUMN j integer', tbl);
    END IF;
  END LOOP;
END $$;

-- 2. Backfill (i, j) for rows that don't have it, from the cell centroid.
-- ST_HexagonGrid with degenerate (point) bounds emits the covering cell; for
-- a cell centroid that is exactly the cell's own (i, j). Then verify the
-- claimed alignment — if any legacy row does NOT sit on the global grid,
-- abort the deploy loudly rather than serve a silently-shifted grid.
DO $$
DECLARE
  spec record;
  n bigint;
  bad bigint;
BEGIN
  FOR spec IN
    SELECT * FROM (VALUES ('hexes_zoom_0', 100000.0), ('hexes_zoom_1', 10000.0))
      AS t(tbl, size)
  LOOP
    EXECUTE format($sql$
      WITH cells AS (
        SELECT hz.pk, g.i::int AS i, g.j::int AS j
        FROM cde.%I hz
        CROSS JOIN LATERAL (
          SELECT i, j FROM ST_HexagonGrid(%s, ST_Centroid(hz.geom))
          ORDER BY i, j LIMIT 1
        ) g
        WHERE hz.i IS NULL
      )
      UPDATE cde.%I hz
      SET i = cells.i, j = cells.j
      FROM cells
      WHERE hz.pk = cells.pk
    $sql$, spec.tbl, spec.size, spec.tbl);
    GET DIAGNOSTICS n = ROW_COUNT;

    IF n > 0 THEN
      RAISE NOTICE 'stable-hex-grid: backfilled (i, j) on % rows of cde.%', n, spec.tbl;
      EXECUTE format($sql$
        SELECT count(*) FROM cde.%I
        WHERE i IS NOT NULL
          AND NOT ST_Equals(geom, ST_SetSRID(ST_Hexagon(%s, i, j), 3857))
      $sql$, spec.tbl, spec.size) INTO bad;
      IF bad > 0 THEN
        RAISE EXCEPTION
          'stable-hex-grid: % row(s) in cde.% do not align with the origin-anchored hex grid; aborting',
          bad, spec.tbl;
      END IF;
    END IF;
  END LOOP;
END $$;

-- 3. Unique natural key; the arbiter for create_hexes()'s ON CONFLICT (i, j).
CREATE UNIQUE INDEX IF NOT EXISTS hexes_zoom_0_ij_key ON cde.hexes_zoom_0 (i, j);
CREATE UNIQUE INDEX IF NOT EXISTS hexes_zoom_1_ij_key ON cde.hexes_zoom_1 (i, j);

-- 4. Drop the per-point hex polygon columns (their GIST indexes go with them).
DO $$
DECLARE
  col text;
BEGIN
  FOREACH col IN ARRAY ARRAY['hex_zoom_0', 'hex_zoom_1'] LOOP
    IF EXISTS (
      SELECT 1 FROM pg_attribute
      WHERE attrelid = 'cde.points'::regclass AND attname = col AND NOT attisdropped
    ) THEN
      EXECUTE format('ALTER TABLE cde.points DROP COLUMN %I', col);
    END IF;
  END LOOP;
END $$;

COMMIT;
