CREATE EXTENSION IF NOT EXISTS postgis;
CREATE schema cioos_api;
CREATE TABLE cioos_api.servers (pk SERIAL PRIMARY KEY, url TEXT UNIQUE);
-- from CSV: ,erddap_url,dataset_id,cdm_data_type,dataset_standard_names

CREATE TABLE cioos_api.datasets (
    pk serial PRIMARY KEY,
    dataset_id text,
    erddap_url text REFERENCES cioos_api.servers(url),
    cdm_data_type text,
    dataset_standard_names text[],
    ckan_record jsonb,
    profile_variable text,
    ckan_url text,
    UNIQUE(dataset_id, erddap_url)
);

-- from csv: server,dataset_id,time_min,time_max,latitude_min,latitude_max,longitude_min,longitude_max
DROP TABLE IF EXISTS cioos_api.profiles;
CREATE TABLE cioos_api.profiles (
    pk serial PRIMARY KEY,
    geom geometry(Point,4326),
    dataset_pk integer REFERENCES cioos_api.datasets(pk),
    server_pk integer REFERENCES cioos_api.servers(pk),
    erddap_url text,
    dataset_id text,
    time_min timestamp with time zone,
    time_max timestamp with time zone,
    latitude_min double precision,
    latitude_max double precision,
    longitude_min double precision,
    longitude_max double precision,
    profile_id text
);
-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.
-- Table Definition ----------------------------------------------
-- DROP VIEW cioos_api.combined
CREATE VIEW cioos_api.combined AS
SELECT profiles.pk,
    profiles.time_min,
    profiles.time_max,
    profiles.latitude_min,
    profiles.latitude_max,
    profiles.longitude_min,
    profiles.longitude_max,
    profiles.geom,
    datasets.dataset_id,
    datasets.erddap_url,
    datasets.cdm_data_type,
    datasets.dataset_standard_names,
    profiles.latitude_min = profiles.latitude_max
    AND profiles.longitude_min = profiles.longitude_max AS is_point
FROM cioos_api.profiles
    LEFT JOIN cioos_api.datasets ON datasets.pk = profiles.dataset_pk
    LEFT JOIN cioos_api.servers ON servers.url = datasets.erddap_url;


