name: Test

on:
  push:
  pull_request:

jobs:
  docker:
    name: Build and test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start containers
        run: |
          mv .env.sample .env
          docker compose -f "docker-compose.production.yaml" up -d --build --quiet-pull

      - name: Run ERDDAP harvester on sample dataset
        run: cp ./harvest_config.sample.yaml ./harvest_config.yaml && docker compose -f "docker-compose.production.yaml" up harvester

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        working-directory: ./test
        run: 
          npm ci --quiet
          apt-get update
          apt-get install -y libnss3 libasound-dev

      - name: Test API endpoints
        working-directory: ./test
        run: node test_api_endpoints.js

      - name: Test frontend loads without errors
        working-directory: ./test
        run: node frontend_loads_without_errors.js

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.production.yaml" down
