name: Build and Test

on:
  push:
    paths:
      - "downloader/**"

jobs:
  build-and-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.22"

      - name: Install downloader and harvester
        run: |
          pip install -q ./harvester
          pip install -q ./downloader

      - name: Run downloader test files
        working-directory: ./downloader
        run: sh test_downloader.sh
