name: Build and Test

on:
  push:
    paths:
      - "downloader/**"

jobs:
  build-and-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"

      - name: Install dependencies
        working-directory: ./downloader
        run: uv sync --lockfile

      - name: Run downloader test files
        working-directory: ./downloader
        run: uv run pytest
